### ISSUE TITLE
[BUG] Missing Engine Sound

### ISSUE THREAD

**Issue by n0tsiege** [notsiege-development/SIEGE-CAR-PACK#7]
**Release Version**: 1.0

**Vehicle the issue is happening with**: m4comp, chr20

**Detailed issue description**: No engine sound or other sounds.

**Reproduction Steps (if applicable)**: N/A

**Comment by Hamy-os** [comment]
fixed: https://github.com/notsiege-development/SIEGE-CAR-PACK/commit/81c1e898574d914bbd345366cfcfd8b8ac569525
